version: '3'
services:
  react-app:
    build: 
      context: ./frontend/MyApp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    # depends_on:
    #   - react-app
      # - backend
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "5000:5000"
