version: '3.8'
services:
  react-app:
    build: ./frontend/MyApp/
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./frontend/MyApp/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - react-app
      # - backend
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "5000:5000"
